//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySystem_admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySystemDBEntities : DbContext
    {
        public MySystemDBEntities()
            : base("name=MySystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<VendorCertification> VendorCertification { get; set; }
        public virtual DbSet<VendorContact> VendorContact { get; set; }
        public virtual DbSet<VendorMainCustomer> VendorMainCustomer { get; set; }
        public virtual DbSet<VendorMainProduct> VendorMainProduct { get; set; }
        public virtual DbSet<VendorManufacture> VendorManufacture { get; set; }
        public virtual DbSet<VendorTradeTerm> VendorTradeTerm { get; set; }
    }
}
