//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySystem_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorCertification
    {
        public string VendorId { get; set; }
        public string Certificate { get; set; }
        public string CertificateName { get; set; }
        public string Organization { get; set; }
        public Nullable<System.DateTime> CertificationDate { get; set; }
        public string VendorVendorId { get; set; }
    }
}
